### PR TITLE
Improved/distinct textures for Venus and Uranus, textures for Jovian/Saturnian moons

### PR DESCRIPTION
**Pull request by Noobly-Walker**
The old texture for Venus resembles its naked surface, which looks a bit too much like Mars, and wouldn't be seen anyway through the thick cloud cover. The new texture displays the cloud cover.

Uranus' old texture was sideways (Uranus' axis is tipped nearly 90°), and was too visually similar to Neptune, so it was rotated, and its rings were added to the texture.

### CODE REVIEW

**Comment by Noobly-Walker** [comment]
I found out that some planets seem to have random rotation in the sky, so rotating Uranus' texture was unnecessary, but there's still the ring going for it.

**Comment by Noobly-Walker** [comment]
i'm not good at github, the star colors should be on a different branch, to become a different pull

**Comment by Povstalec** [comment]
The changes seem really cool. There are some slight adjustments I want to add to it for the sake of maning the stuff like star color configurable, but yeah, I'll probably be merging it tomorrow.

**Comment by Noobly-Walker** [comment]
I have a few more ideas, too, but I'm going to have branches on my fork moving forward for each idea I implement. Should hopefully make it easier for you to manage individual submissions, right?

**Comment by Povstalec** [comment]
> I have a few more ideas, too, but I'm going to have branches on my fork moving forward for each idea I implement. Should hopefully make it easier for you to manage individual submissions, right?

Most definitely.

Ideally it would be nice if the changes were on 1.19.3 and not 1.20.1, because 1.19.3 is a good middle ground between 1.19.2 and 1.20.1 in terms of rendering code, so it would save me some time taken by changing stuff that's version specific, because forwardporting is easier than backporting.

No need to change anything here, since I don't see anything use version specific code here, so it should be fine if I just git cherry pick changes to older mod versions.

**Pull request merged**
